### ISSUE TITLE
Minor map bugs

### ISSUE THREAD

**Issue by enterprisecock** [PartyKarts-io/UnityGame#23]
### Monza tire stack without collision
Location: Pit entrance
![Monza - Tire stack](https://github.com/PartyKarts-io/UnityGame/assets/133701161/42bf327d-69d5-4f51-91ca-8667ced273e8)

### Monza grass, gravel, sand without speed loss
Driving on any _non_-track surface doesn't incur a speed penalty like on _Party Parks_.

### Monza audio issue
The audio shifts from stereo to the right side only when driving through _Curva Grande_.
Then, at _Variante Ascar_, it shifts to the left side only.

### Spa crash barrier without collision
Location: _Eau Rouge_
![Spa - Crash Barrier](https://github.com/PartyKarts-io/UnityGame/assets/133701161/5bdc0fc7-6213-46e0-8b5b-a4443c9af88a)

### Spa grass, gravel, sand without speed loss
Driving on any _non_-track surface doesn't incur a speed penalty like on _Party Parks_.

### Spa track markers / objects don't have physics
Objects completely lack physics on Spa.
![Spa - Track Marker](https://github.com/PartyKarts-io/UnityGame/assets/133701161/16867bab-490a-488b-9991-e7dd6cd281db)

**Comment by PartyKarts** [comment]
https://github.com/PartyKarts-io/UnityGame/pull/31

This PR fixes the collider issues you've reported - I will close this bug and re-open another for tracking the friction material issue at the new tracks
