### ISSUE TITLE
Car bugs

### ISSUE THREAD

**Issue by enterprisecock** [PartyKarts-io/UnityGame#24]
## Fifth gear not shifting down
Car shifts from fourth to fifth at ~405 km/h, but doesn't downshift back to fourth before ~140 km/h

## Car takes ages to slown down at less than 5 km/h
At less than 5 km/h the car seems to have no grip and won't stop until the handbrake is pressed.
Also makes a burnout at 0 km/h.

**Comment by PartyKarts** [comment]
https://github.com/PartyKarts-io/UnityGame/pull/30/commits/85dfa826bed30d7f338f44ab4d4d50b24225809d

This has been fixed via this commit + PR
