### ISSUE TITLE
UI Bug

### ISSUE THREAD

**Issue by enterprisecock** [PartyKarts-io/UnityGame#25]
Selecting cars and maps with Q/E doesn't actually select them. It will switch your view, so if i click _E_ on pic below I'll see Spa, but then clicking _select_ will revert the map back to _Party Parks_ when the race actually starts. Same goes for cars.
![firefox_SaKpnxhjZv](https://github.com/PartyKarts-io/UnityGame/assets/133701161/d8057263-8aed-4014-a5ca-7d892a77bcaf)

**Comment by PartyKarts** [comment]
This UI update has been rolled back but that is a great callout - I had not tested with the hotkeys and did not map their actions - this will be fixed when the UI update goes back live

**Comment by PartyKarts** [comment]
https://github.com/PartyKarts-io/UnityGame/commit/f33733279034cdfdb6871ffa81b8ab0c1d4d0e97

Fixed in this commit ^
